# Generated by Django 2.0.2 on 2018-03-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BazyDanych',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('Or', 'Oracle'), ('My', 'MySQL'), ('Po', 'PostgreSQL'), ('Ms', 'MS SQL')], default='My', max_length=2)),
                ('wersja', models.CharField(max_length=40)),
                ('licencja', models.CharField(choices=[('Pl', 'Płatna'), ('Da', 'Darmowa')], default='Da', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Serwery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('nazwa', models.CharField(max_length=100)),
                ('system_operacyjny', models.CharField(choices=[('L', 'Linux'), ('W', 'Windows')], default='W', max_length=1)),
                ('fizyczny_wirtualny', models.CharField(choices=[('F', 'Fizyczny'), ('W', 'Wirtualny')], default='F', max_length=1)),
                ('wersja', models.CharField(max_length=40)),
                ('adres', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SerwerySystemow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serwer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.Serwery')),
            ],
        ),
        migrations.CreateModel(
            name='Systemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(choices=[('IB', 'NASK PIB'), ('SP', 'NASK SA')], default='IB', max_length=2)),
                ('nazwa', models.CharField(max_length=100)),
                ('opis_systemu', models.TextField(max_length=400)),
                ('oprogramowanie', models.CharField(blank=True, max_length=100)),
                ('data_wsparcia', models.DateField(verbose_name='data końca wsparcia')),
                ('administrator_bazy_glowny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_baza_glowny', to='umowy.Administratorzy')),
                ('administrator_bazy_zastepczy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_baza_zastepca', to='umowy.Administratorzy')),
                ('administrator_systemu_glowny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_system_glowny', to='umowy.Administratorzy')),
                ('administrator_systemu_zastepczy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_system_zastepca', to='umowy.Administratorzy')),
                ('baza_danych', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.BazyDanych')),
            ],
        ),
        migrations.CreateModel(
            name='UmowyUtrzymaniowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=100)),
                ('dataUmowy', models.DateField(verbose_name='Data podpisania')),
                ('dataKoncaUmowy', models.DateField(verbose_name='Data końca obowiązywania')),
                ('wsparcie_techniczne', models.TextField(max_length=400)),
                ('plik_umowy', models.FileField(upload_to='')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umowy.Systemy')),
            ],
        ),
        migrations.AddField(
            model_name='serwerysystemow',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='umowy.Systemy'),
        ),
    ]
